### ISSUE TITLE
Ms Julie Norris 

### ISSUE THREAD

**Issue by mum59** [AU-COVIDSafe/mobile-android#10]
The covid 19 app on my phone stops working battery optimisiat must be disabled.  I keep turning this function off. After a while it turns back on and disables the app.  I have uninstalled and reinstalled but still get the same issue. 
My phone is OPPO A73
Model CPH1725
ColorOs version V3.2
Android 7.1.1

**Comment by covidsafe-support** [comment]
Hi @mum59 - for troubleshooting and answers to your questions about using the COVIDSafe app, you can use our online help any time, email us, or call our helpline - support@covidsafe.gov.au or 1800 020 080.

**Comment by mum59** [comment]
I have followed the suggestion in you QA but still having the same issue 
> The covid 19 app on my phone stops working battery optimisiat must be disabled. I keep turning this function off. After a while it turns back on and disables the app. I have uninstalled and reinstalled but still get the same issue.
> My phone is OPPO A73
> Model CPH1725
> ColorOs version V3.2
> Android 7.1.1

**Comment by jimmo** [comment]
@mum59 This is a deliberate feature in COVIDSafe (introduced in v1.0.33) that happens to interact poorly with ColorOs battery optimisation features on Oppo phones. Unfortunately unless you can find a way to permanently disable battery optimisation completely, there's nothing you can do to prevent this happening. (It's definitely not something that you've done wrong).

Might be worth looking at https://oppo.custhelp.com/app/answers/detail/a_id/3597/~/power-saver-features

@covidsafe-support It might be worth looking into this as it's likely causing issues for anyone with Oppo phones. Could the battery optimiser detection be more sophisticated?

**Comment by mum59** [comment]
thank you for your response, i will turn on thr app only when i go out

cheers
julie

________________________________
