### ISSUE TITLE
Run in Background permission keeps getting revoked

### ISSUE THREAD

**Issue by kurahaupo** [AU-COVIDSafe/mobile-android#16]
I have an Oppo phone running their badged version of Android called "ColorOS", which is basically stock Android with some pretty apps.

The problem is that their power management is extremely aggressive, and the "run in background" permission is revoked within half an hour after every time I grant it.

Is there any setting I can change to improve this, or is there something you can negotiate with Oppo?

**Comment by kurahaupo** [comment]
I have observed this behaviour in versions:
* 1.0.33
* 1.0.39

**Comment by covidsafe-support** [comment]
Hi @kurahaupo - thanks for making contact. For advice regarding disabling battery optimisation, please see the following help topic:

https://www.covidsafe.gov.au/help-topics.html#disable-battery-optimisation-android

If you require more assistance, please contact the COVIDSafe support area, by email using support@covidsafe.gov.au or by phone on 1800 020 080.
