### ISSUE TITLE
ColorOS battery optimisation problems

### ISSUE THREAD

**Issue by eleanor-em** [AU-COVIDSafe/mobile-android#19]
As reported by both #10 and #16, the ColorOS variant of Android used for Oppo phones has very aggressive battery optimisation that repeatedly turns it back on for COVIDSafe, rendering the app unable to open because it checks that battery optimisation is disabled before starting up. Following the help topics does not work for users with this issue, because ColorOS does not behave as the help topic expects.

Note the help topic has Oppo specific instructions, but it seems that users are still experiencing issues. Has this been investigated?

This could be addressed with more sophisticated logic to handle this specific case. See @jimmo's comments reproduced below:

***

@mum59 This is a deliberate feature in COVIDSafe (introduced in v1.0.33) that happens to interact poorly with ColorOs battery optimisation features on Oppo phones. Unfortunately unless you can find a way to permanently disable battery optimisation completely, there's nothing you can do to prevent this happening. (It's definitely not something that you've done wrong).

Might be worth looking at https://oppo.custhelp.com/app/answers/detail/a_id/3597/~/power-saver-features

@covidsafe-support It might be worth looking into this as it's likely causing issues for anyone with Oppo phones. Could the battery optimiser detection be more sophisticated?

_Originally posted by @jimmo in https://github.com/AU-COVIDSafe/mobile-android/issues/10#issuecomment-664076873_

**Comment by covidsafe-team** [comment]
Thanks for raising this. We have provided advice on Oppo battery use via help topics at https://www.covidsafe.gov.au/help-topics.html

**Comment by kurahaupo** [comment]
Referring to the help page as part of the resolution of this issue does not instill confidence, especially as the text is unchanged from when the issue was raised. (People reporting this issue had already used the steps on that page and found them badly wanting.)

Can you please advise what measures were taken to stop Oppo devices from spontaneously changing the power-saving/background-running setting?

Currently the advice on that page is:

> OPPO phones
> 
> To disable battery optimisation on OPPO phones, you must first check the version by selecting ‘About Phone’ from 'Settings'.
> 
> For OPPO phones with ColorOS 5.0 and above:
> 
> * Go to the OPPO home screen.
> * Long press on the COVIDSafe app until you see the 'App Info' option, tap on it.
> * Tap on 'Power Saver'.
> * Tap on 'Allow Background Running'.
> 
> For OPPO phones with ColorOS version 3.2 and below:
> 
> * Go to 'Settings'.
> * Tap on 'Battery'.
> * Tap on 'Energy Saver' and look for the COVIDSafe app.
> * Disable all options.
> 
> If you still have issues after following the instructions, you may need to contact your device manufacturer or mobile provider for advice.

If they have ColorOS 6 or later, the instructions should be different.

Please add:

> For OPPO phones with ColorOS 7.0 and above:
>
> * Go to the OPPO home screen.
> * Long press on the COVIDSafe app until you see the 'App Info' option, tap on it.
> * Tap on 'Battery'.
> * Tap on 'Run in background'
