### ISSUE TITLE
Please allow issues to be reopened

### ISSUE THREAD

**Issue by kurahaupo** [AU-COVIDSafe/mobile-android#20]
While this is a follow-up to #16, and thus mostly duplicate of #19, it is also a plea not to close and lock issues.
* Allow time for additional feedback before closing issues, regardless of any resolution.
* Keep "known problem" issues live, so that users can see that it's already in hand, and you _don't_ wind up with multiple issues reporting the same problem. This also allows you to delete inappropriate comments from a single issue, when deleting entire issues is not possible.
* Allow issues to be re-opened when it turns out that they're not resolved; only lock issues from vexatious complainants.

**Comment by kurahaupo** [comment]
While this is mostly duplicate of #19, it is also a plea not to close and lock issues.
* Allow time for additional feedback before closing issues, regardless of any resolution.
* Keep "known problem" issues live, so that users can see that it's already in hand, and you _don't_ wind up with multiple issues reporting the same problem. This also allows you to delete inappropriate comments from a single issue, when deleting entire issues is not possible.
* Allow issues to be re-opened when it turns out that they're not resolved; only lock issues from vexatious complainants.

**Comment by anomaly256** [comment]
Closing #16 out of hand without realizing it is actually a bug that needs addressing is a mistake.  Locking it though, preventing discourse on the subject and almost guaranteeing it will never be addressed is just hostile.  This is an important project.  Don't mismanage it this way please.
</my_own_2_cents>

**Comment by covidsafe-team** [comment]
Hi @kurahaupo thanks for your feedback we've taken it onboard.
