### ISSUE TITLE
complementary opportunities 

### ISSUE THREAD

**Issue by mediaprophet** [AU-COVIDSafe/mobile-android#21]
see: https://github.com/AU-COVIDSafe/mobile-ios/issues/14#issuecomment-668347785 

issue topic illustrated with the hope others might have other (good?) ideas...

**Comment by covidsafe-team** [comment]
Thanks @mediaprophet . As noted here COVIDSafe will continue to focus on Bluetooth tracing. QR Code integration is not currently within the scope of COVIDSafe.

**Comment by mediaprophet** [comment]
Given bluetooth beacon work / research since 2001, i think you'll come-up
against spam protection related protections linked to the policies applied
to the bluetooth radio.

unless you want global ID based solutions, in which case it would be
cheaper to goto visa / mastercard.

but you're the experts paid the 'big bucks'.  i'm sure you're honest about
all of this...

cheers.

tim.
