### ISSUE TITLE
FYI: Insecure random regression in upstream Herald

### ISSUE THREAD

**Issue by jimmo** [AU-COVIDSafe/mobile-android#35]
I have no idea what COVIDSafe's plans are for integrating upstream Herald changes, but please be aware that a recent change has made it possible again to re-identify devices by their PseudoDeviceAddress, similar to the issue I raised on 2nd December.

Please do not merge upstream Herald code into COVIDSafe until this is fixed.

See https://github.com/vmware/herald-for-android/issues/110

**Comment by covidsafe-team** [comment]
Thank you @jimmo for this suggestion and all your advice on this issue. We have incorporated a fix based on the advice you and Alwen provided to us. We intend to integrate the libraries in future and will ensure that our current fix is maintained.
