### ISSUE TITLE
Very frequent re-initialisation of SecureRandom in PseudoDeviceAddress

### ISSUE THREAD

**Issue by vteague** [AU-COVIDSafe/mobile-android#37]
I think you might find that the constant re-initialisation of SecureRandom in PseudoDeviceAddress eventually runs out of entropy and blocks, especially if the device is left alone for a few hours.

Specifically, it looks to me as if rather than getting the next few bytes from an already-seeded SecureRandom, which is what I'd expect this function to do:

```
public PseudoDeviceAddress() {
    byte[] encode = encode(getSecureRandomLong());
    this.data = encode;
    this.address = decode(encode);
}
```

it actually generates a new SecureRandom object, which if I understand rightly will be re-seeded using device randomness.

```
protected static final long getSecureRandomLong() {
    return new SecureRandom().nextLong();
}
```

You really didn't need to do it this way - I'm pretty sure that @jimmo and @chrisculnane and Alwen Tiu have already explained that the right way to do this is seed the SecureRandom object once (and then re-seed infrequently), then generate the actual random values using repeated calls to nextBytes().

I am not certain whether this will cause problems in practice, but it's possible this will cause some people's devices' sources of randomness to block, which will affect not only COVIDSafe but also other apps that depend on device randomness.  I'll leave my device running quietly overnight and let you know what happens.

**Comment by jimmo** [comment]
Yes, exactly what @vteague said.

The comments in the code that has been copied from Herald's RandomSource.java explain this.

Use getRandomSingletonLong() instead. It's not clear why any other code needed to be copied from Herald.

Or better yet, see the extensive analysis and suggestions at https://github.com/vmware/herald-for-android/issues/110

**Comment by covidsafe-team** [comment]
Hi @vteague and @jimmo - thanks for raising this, The latest release includes a change that addresses this issue.
