### ISSUE TITLE
COVIDSafe doesn't alert for new versions

### ISSUE THREAD

**Issue by jimmo** [AU-COVIDSafe/mobile-android#42]
I have v1.13 installed, with auto-updates disabled.

COVIDSafe seems totally unaware that there have been two releases since then.

I have never seen a notification popup from the push-notification functionality that was added before 1.13, and the home screen of the app doesn't show anything.

**Comment by covidsafe-team** [comment]
Hi @jimmo - thanks for raising this. We will investigate.

**Comment by covidsafe-team** [comment]
Hi @jimmo - thanks for raising this. We've made a change to our process, and the update alerts have been working more reliably for the last two releases.
