### ISSUE TITLE
COVIDSafe 2.3 crashes when accessing Help Topics

### ISSUE THREAD

**Issue by alwentiu** [AU-COVIDSafe/mobile-android#47]
Accessing the Help Topics menu through Settings crashes COVIDSafe v2.3. Accessing it through Home menu works fine.

**Comment by jimmo** [comment]
I see this too.

Although the version number in the app says 2.3, it appears to be the same features as #46 (i.e. restrictions).

**Comment by covidsafe-team** [comment]
Hi @alwentiu, 
Thanks for raising this - and @jimmo for verifying. We will have a fix for this in the next release.

**Comment by covidsafe-team** [comment]
Hi @alwentiu,
This bug was fixed in the release last week. Thanks for raising it.
