### ISSUE TITLE
COVIDSafe doesn't check that location is enabled

### ISSUE THREAD

**Issue by jimmo** [AU-COVIDSafe/mobile-android#6]
In order to do an LE scan, you need to have the fine (or coarse) location permission (which COVIDSafe has), however the global "Use Location" setting acts as a kind of system-wide toggle for these permissions. See (for example) [checkCallerHasCoarseLocation](https://cs.android.com/android/platform/superproject/+/master:packages/apps/Bluetooth/src/com/android/bluetooth/Utils.java;l=394;drc=master) which is used by BluetoothLeScanner.

`BluetoothMonitoringService` [checks for the fine location permission](https://github.com/AU-COVIDSafe/mobile-android/blob/c16533add66e043f5f6e841df8921afff8593d04/app/src/main/java/au/gov/health/covidsafe/services/BluetoothMonitoringService.kt#L195) and that the adaptor is enabled, but doesn't explicitly check that location is enabled.

The result is that the app runs as if everything is fine (and it is still running the advertiser & peripheral role just fine), but every time it starts a scan:

```
06-24 21:29:04.952  7432  7450 D BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=7 mScannerId=0
06-24 21:29:04.961  1749  1768 E BluetoothUtils: Permission denial: Location is off.
06-24 21:29:12.975  7432  7432 D BluetoothAdapter: isLeEnabled(): ON
```

Compare this to another app like [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) which will indicate that location is not enabled if the user attempts to scan.

Related, why does COVIDSafe use `ACCESS_FINE_LOCATION` when `ACCESS_COARSE_LOCATION` would be sufficient for BLE scanning.

Thanks @vteague for noticing this!

**Comment by covidsafe-support** [comment]
Hi @jimmo - nice catch! we've created a ticket for this in our backlog.

I'm seeking more clarification for you on why `ACCESS_FINE_LOCATION` and not `ACCESS_COARSE_LOCATION` - I'll update this issue when I have some more information for you.

**Comment by covidsafe-support** [comment]
Hi @jimmo - just a quick update for you. We believe we can change to `ACCESS_COARSE_LOCATION` so this should be included in a future update.

**Comment by eleanor-em** [comment]
Hey crew -- worth thinking about whether you should allow people to use the app even without location, as long as they're warned about it not working.

For example, you could give users a prompt: "Warning: location services are currently disabled. The app will not be as effective. Would you like to turn them back on?"

This would actually be an advantage over the Google & Apple Notification Exposure API, because on Android it will not allow you to use it at all without enabling location.

**Comment by vteague** [comment]
I support @eleanor-em's suggestion.  I refuse to run Google Location Services unless I really need them, and would rather live with the occasional missed contact.  You can warn users without forcing them to enable location.

**Comment by jacobgoodo** [comment]
> Hey crew -- worth thinking about whether you should allow people to use the app even without location, as long as they're warned about it not working.
> 
> For example, you could give users a prompt: "Warning: location services are currently disabled. The app will not be as effective. Would you like to turn them back on?"
> 
> This would actually be an advantage over the Google & Apple Notification Exposure API, because on Android it will not allow you to use it at all without enabling location.

Unfortunately, the app is unable to get any Bluetooth permissions if the location permission isn't enabled - the app would not function at all due to Android policy

**Comment by yaakov-h** [comment]
This is talking about whether or not location services is enabled, not whether or not the app is granted the `ACCESS_FINE_LOCATION`/`ACCESS_COARSE_LOCATION` permissions.

**Comment by a1291762** [comment]
TIL I have not been using the app despite it being installed and running since day 1 :(

Bad system apps (Google Maps!) mean that I've had location off globally unless I was actually using it for navigation.

Covidsafe is happy if I turn it on... But what about android 10's "allow only while app is running"? Will that also defeat covidsafe?

Annoying that GPS and Bluetooth are tied together like this. But that's not your fault.

**Comment by a1291762** [comment]
To answer my own question... As long as covidsafe targets api 28 then it looks to be safe. Once it targets api 29 it might need some changes.
https://developer.android.com/about/versions/10/privacy/changes#app-access-device-location

**Comment by a1291762** [comment]
I was just going to mention this but someone already filese a separate issue. The check/notification is not catching all cases.
https://github.com/AU-COVIDSafe/mobile-android/issues/13

**Comment by covidsafe-support** [comment]
Hi @jimmo, thanks again for reporting this issue. In the v1.0.39 release we adjusted the location permission to `ACCESS_COARSE_LOCATION` and we have added a check to the app to make sure that location is enabled. We are aware of the notification and UI issues described in https://github.com/AU-COVIDSafe/mobile-android/issues/13 which we will track in that issue.
