### ISSUE TITLE
Apple/Google privacy preserving COVID-19 contact tracing. 

### ISSUE THREAD

**Issue by benos5000** [AU-COVIDSafe/mobile-android#9]
Good morning. Can you please add support for the Apple/Google privacy preserving COVID-19 contact tracing. Thanks

https://www.apple.com/covid19/contacttracing

**Comment by covidsafe-support** [comment]
Hi @benos5000, thanks for raising this. We are working with Apple and Google as they develop contact tracing technology that could enhance the COVIDSafe application and, when appropriate, we will communicate how the COVIDSafe application can leverage the technology.
